---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-golang-hello-world-web
  # allow for override: kubectl -n <ns> apply ...
  #namespace: default
spec:
  selector:
    matchLabels:
      app: prom-golang-hello-world-web
  replicas: 1
  template:
    metadata:
      labels:
        app: prom-golang-hello-world-web
      annotations:
        sidecar.istio.io/inject: "false"

    spec:

      containers:
      - name: prom-golang-hello-world-web
        image: ghcr.io/fabianlee/docker-prom-golang-hello-world-web:latest

        # resource limits
        resources:
          requests:
            memory: "8Mi"
            cpu: "500m" # half a vcpu
          limits:
            memory: "16Mi"
            cpu: "1000m" # whole vcpu

        env:

        # 404 if request not to this context
        - name: APP_CONTEXT
          value: "/golang-hello/"

        # default message
        - name: MESSAGE_TO
          value: "World"

        # listening port
        - name: PORT
          value: "8080"


        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: prom-golang-hello-world-web-service
  #namespace: default
  labels:
    app: prom-golang-hello-world-web
spec:
  ports:
  # port=available to other containers
  - port: 8080
    name: http
    # targetPort=exposed from inside container
    targetPort: 8080
    protocol: TCP
  selector:
    app: prom-golang-hello-world-web
